name: Remote Dispatch

on:
  push:
    branches:
      - "[a-zA-Z]?[0-9]*"

jobs:
  dispatch-to-validation-repo:
    runs-on: solinas-small
    steps:
       ### Parse branch and set user branch in env
       - name: Parse user branch
         run: |
           BRANCH=`echo "$GITHUB_REF" | sed 's/refs\/heads\/*//'`
           SHORTREPO=`echo "$GITHUB_REPOSITORY" | sed 's/cloud-curriculum\///'`
           echo "user_branch=$BRANCH" >> $GITHUB_ENV
           echo "short_repo=$SHORTREPO" >> $GITHUB_ENV
        
       - name: Create GH App Token
         uses: actions/create-github-app-token@v1
         id: app-token
         with:
           app-id: ${{ secrets.CC_TECH_INTEGRATION_APP_ID }}
           private-key: ${{ secrets.CC_TECH_INTEGRATION_PRIVATE_KEY }}
           owner: cloud-curriculum # We need to have access to all repositories in the org, omitting the owner would only give access to the current repository https://github.com/actions/create-github-app-token?tab=readme-ov-file#repositories

       - name: Dispatch
         run: |
           curl -X POST https://github.tools.sap/api/v3/repos/cloud-curriculum/exercises-tracking-internal/dispatches \
           -H 'Accept: application/vnd.github+json' \
           -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
           --data '{"event_type": "dispatch-validation;'${{ env.short_repo }}';'${{ env.user_branch }}'", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'","ref": "'"$GITHUB_REF"'" }}'
